name: Run AQI Script

on:
  schedule:
    - cron: '30 9 * * *'  # Runs every day at 3 PM IST (9:30 AM UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # Your Supabase URL secret
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}  # Your Supabase API Key secret

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AQI script
        run: python script.py
